return type Fixes (Null Return Error fix)
imdhemy/google-play-billing pull request #8
Opened 2021-06-17 07:54 UTC by malikzeeshaan

2021-06-25 06:39 UTC, jbagaresgaray commented
@imdhemy I would love to see this merge on the main branch.... I hope it will be reviewed

2021-08-01 17:02 UTC, imdhemy commented on src/Subscriptions/SubscriptionPurchase.php
> +    public function getIntroductoryPriceInfo(): ?IntroductoryPriceInfo
What about returning `null` if the `introductoryPriceInfo` is null and create the `IntroductoryPriceInfo` object otherwise!

2021-08-01 17:04 UTC, imdhemy requested changes

2021-08-01 17:04 UTC, imdhemy commented on src/Subscriptions/SubscriptionPurchase.php
> +    public function getPriceChange(): ?SubscriptionPriceChange
The same idea applies here!

2021-08-01 17:04 UTC, imdhemy commented on src/Subscriptions/SubscriptionPurchase.php
> +    public function getCancellation(): ?Cancellation
And here!

2021-08-01 17:04 UTC, imdhemy commented on src/Subscriptions/SubscriptionPurchase.php
> +    public function getPromotionType(): ?PromotionType
And here!

2021-08-01 17:04 UTC, imdhemy commented on src/Subscriptions/SubscriptionPurchase.php
> +    public function getAcknowledgementState(): ?AcknowledgementState
And finally here!

2021-08-01 17:10 UTC, imdhemy commented
Hi @malikzeeshaan !

Sorry for being late! And thank you for your contribution.
I'd like to see this merged too, @jbagaresgaray !

I added some requests to change, you can use [this class as a reference ](https://github.com/imdhemy/google-play-billing/blob/feature/testing/src/Products/ProductPurchase.php).


And finally, could you please update this PR to be merged into the `develop` branch instead of `master`.

2021-08-07 14:50 UTC, imdhemy commented
@malikzeeshaan 
Hopefully! Everything is going well!

This is a friendly reminder to apply the requested changes in case you are still interested in contributing.

Currently, I'm working on a new release, and I want to merge your PR. Ping me on comments or email **(imdhemy[at]gmail.com)** before the next weekend, otherwise, I'll close the PR due to inactivity. Sure, I'll be sad about that 😞

2021-08-15 20:48 UTC, kkyryl commented
hey guys! i was dealing with a similar issue — the same concept also applies to getExternalAccountId, getObfuscatedExternalAccountId etc — all of them potentially return NULL rather than String. Maybe it would make sense to address this in this PR.

2021-09-20 20:11 UTC, imdhemy commented
Closed due to inactivity.

2021-09-20 20:11 UTC, closed without merging

2021-09-21 19:34 UTC, malikzeeshaan commented
I'm sorry Mohamed Eldhemy for this laye reply. I just checked my email. Are
you still interested?


On Tue, Sep 21, 2021, 1:11 AM Mohamad Eldhemy ***@***.***>
wrote:

> Closed due to inactivity.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/imdhemy/google-play-billing/pull/8#issuecomment-923259764>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALXINNQLJAEDIAWPEMDEDALUC6IP5ANCNFSM463C5SLQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>